# Generated by Django 2.2 on 2019-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampledjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indeedjobs',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='indeedjobs',
            name='job_url',
            field=models.URLField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
