# Generated by Django 2.2 on 2019-06-19 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampledjango', '0002_auto_20190619_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeedjobs',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
