# Generated by Django 2.2 on 2019-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampledjango', '0003_indeedjobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeedjobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
