# Generated by Django 2.2 on 2019-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampledjango', '0004_auto_20190619_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeedjobs',
            name='job_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
