# Generated by Django 2.2 on 2019-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampledjango', '0005_auto_20190619_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeedjobs',
            name='pub_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
